### ISSUE TITLE
Insufficient storage problem present in b10

### ISSUE THREAD

**Issue by mokeg67** [Macjutsu/super#82] opened 2023-04-18 12:36 UTC
Hi, unfortunately I am still encountering this Bug, when launching super 3.0b10 via the command line.
I'm using MacOS 13.2.1 on my test machine and have uninstalled the previous version of super before testing 3.0b10.

I have attached the output with `--verbose-mode`

[super.log](https://github.com/Macjutsu/super/files/11208092/super.log)

_Originally posted by @mokeg67 in https://github.com/Macjutsu/super/issues/79#issuecomment-1504759307_

**Comment by davidjimenezm** [comment] 2023-04-18 14:32
I had the same problem, I made a change to lines 3643, 3647, 3653 and 3664 and it seems to work fine now. I replaced _**awk -F '.' '{print $1+1}'**_ with **_awk -F '.' '{print $1+1}' | awk -F ',' '{print $1}'_** to recognize the commas. It's not the most elegant solution but it's the one I've found, I hope it works for you.

**Comment by Macjutsu** [comment] 2023-05-03 14:10
Thanks... this will be fixed in the next release.

**Comment by Macjutsu** [comment] 2023-05-04 14:36
Please try latest release: https://github.com/Macjutsu/super/releases/tag/v3.0-b11

**Closed by Macjutsu** 2023-05-04 14:36 UTC
Labels: bug

**Comment by davidjimenezm** [comment] 2023-05-05 10:30
Hi! Sorry, but I think the problem is still there. Add a sed command for remove "," before dividing it doesnt work because in non-USA regions we use the character "," for float numbers, like you use "." . The command "awk '{print $1/1000000}'" still produces float numbers, so converts 10.324 Gb into 10324 Gb, for example.

The most elegant solution I found is using bc command instead awk for operations, like this:

$(echo "$softwareUpdateLIST" | grep 'Title: macOS' | awk -F ': ' '{print $4}' | grep -o -E '[0-9]+' | awk '{print $1"/1000000 +1"}' | bc)

It's working for me and I think it still work for USA nomenclature.
