### ISSUE TITLE
Super 4.0.3 appears to launch every 60 seconds on some Sonoma Macs (both Intel and Apple Silicon)

### ISSUE THREAD

**Issue by justintrant** [Macjutsu/super#209] opened 2024-03-12 17:22 UTC
Hello @Macjutsu,

Thank you for your hard work in creating such a great tool for the community.

I have noticed as we increase our deployment scope that some Sonoma 14.3.1 Macs appear to exhibit strange behavior whereby super launches every 60 seconds, despite `DeferralTimerWorkflowRelaunch` being set to (in my case) 60 minutes. I have attached logs demonstrating the issue.

It appears that the `StartInterval` set in the LaunchDaemon is being used for this, and the tool is ignoring deferrals.

Is this a known issue?

Thanks again,
Justin.
[super-relaunch-example.txt](https://github.com/Macjutsu/super/files/14576316/super-relaunch-example.txt)

**Comment by tcvall86** [comment] 2024-03-26 14:09
We are seeing the same behaviour on some of our devices.
A user was able to upgrade to 14.4 but the subsequent 14.4.1 that came out ran into this issue. Only happened to one device so far but would be interesting to find the root cause

**Comment by raylinger** [comment] 2024-03-28 12:13
Hello,

since 14.4 this started to happen to all of my clients.

 Usually when a User defers, the log shows the Message
"Status: User chose to defer update for xxx minutes."

```
Status: Soft maximum deferral count of 7 NOT passed with 7 remaining.
super[16021]: IBM Notifier: Restart or defer dialog with a 300 second timeout.
super[16021]: Status: User chose to defer update for 1440 minutes.
super[16021]: Exit: super is scheduled to automatically relaunch at: 2024-02-29:07:35:00
super[16021]: **** S.U.P.E.R.M.A.N. 4.0.2 - CLEAN EXIT ****
```

But now the deferral does not show up in the log at all:

```
Status: Soft maximum deferral count of 7 NOT passed with 1 remaining.
super[52981]: IBM Notifier: Restart or defer dialog with a 300 second timeout.
super[52981]: **** S.U.P.E.R.M.A.N. 4.0.2 - CLEAN EXIT ****
```

**Comment by Macjutsu** [comment] 2024-05-17 19:32
Please try the latest release of super as it may resolve this issue: https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1

**Comment by alogeallen** [comment] 2024-07-26 12:50
I am facing similar problem. The deferral time shows in the log but super relaunches before the time that the users have chosen to defer. It always pops up again every 20 minutes approximately.

**Comment by Macjutsu** [comment] 2024-07-26 21:37
@alogeallen Please check the local super.log on the device. It will show the following text `**** S.U.P.E.R.M.A.N. 5.0.0-beta2 - LAUNCHDAEMON ****` when started via the `super` LaunchDaemon. However, if you see `**** S.U.P.E.R.M.A.N. 5.0.0-beta2 - SUPER STARTUP ****` text then there is another process starting `super`.

**Comment by Macjutsu** [comment] 2024-09-10 03:48
There have been so many changes to the latest version of `super` that I'm closing this issue.

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

If you find it persists with the latest builds of `super` please open a new issue.

**Closed by Macjutsu** 2024-09-10 03:48 UTC
Labels: question
