### ISSUE TITLE
getting error - Failed to send MDM install update/upgrade request. Verify that the Jamf Pro API account XXX has the privileges "Jamf Pro Server Objects > Computers > Create & Read" and "Jamf Pro Server Actions > Send Computer Remote Command to Download and Install macOS Update".

### ISSUE THREAD

**Issue by msmith-wenona** [Macjutsu/super#104] opened 2023-07-07 00:41 UTC
I am getting this error on the super run.
I have checked and triple checked that this account is setup in jamf correctly.
![image](https://github.com/Macjutsu/super/assets/133932915/0f176045-ec17-4fed-9e4e-1b672dbb7e3f)
![image](https://github.com/Macjutsu/super/assets/133932915/84ee480a-bd7e-4ad7-a102-b12fed0901e3)

I have set the password multiple times to make sure it is correct :-)

It happens when upDATING or when upGRADING.

anyone else seeing this or any thoughts on what to do?

Cheers
Michael

**Comment by Macjutsu** [comment] 2023-07-07 01:08
Have you checked the latest documented requirements?

https://github.com/Macjutsu/super/wiki/Apple-Silicon-Jamf-Pro-API-Credentials#jamf-pro-api-account-privileges

**Comment by msmith-wenona** [comment] 2023-07-07 01:54
thank you for that. Yes we are on JAMF 10.47.
I added the new permissions and it definitely got further.
But still failed.

the only error I can see that might be related is:
`Error: Installation of macOS update/upgrade timed out after 600 seconds, trying again in 3600 seconds.`

I have verbose mode on so let me know any of the log files that might show more details.

**Comment by Macjutsu** [comment] 2023-07-07 14:14
This is likely not an issue directly with `super`, instead this is likely a very common failure of the MDM process, usually on the local computer.

Check some of the other logs per this documentation: https://github.com/Macjutsu/super/wiki/Troubleshooting#mdmcommandlog

**Comment by redsee83** [comment] 2023-07-14 00:30
@msmith-wenona I'm having the same issue, after adding the additional server permissions for jamf 10.47, im getting the same mdm failure. Wondering if this was ever resolved for you?

**Comment by redsee83** [comment] 2023-07-14 00:30
@msmith-wenona Im having the same issue, after adding additional server permissions im getting the same failure. Wondering if this was ever resolved for you?

**Comment by Macjutsu** [comment] 2023-07-14 01:23
@redsee83 Have you followed the documentation and checked the mdmCommand.log or mdmWorkflow.log?

https://github.com/Macjutsu/super/wiki/Troubleshooting#mdmcommandlog

**Comment by redsee83** [comment] 2023-07-14 01:31
Yes I have, I have incrementally adjusted the following timeouts without any luck. Attached logs for reference.
`Error: Push workflow for macOS update/upgrade via MDM failed, trying again in XXXX seconds.`

# The number of seconds to timeout the macOS installation workflow if no progress is reported.
macOSInstallerTimeoutSECONDS=900

# The number of seconds to timeout MDM commands if no response is reported.
mdmTimeoutSECONDS=1200

# The number of seconds to timeout the MDM download/prepare workflow if no progress is reported.
mdmWorkflowTimeoutSECONDS=1800

[mdmCommand.log](https://github.com/Macjutsu/super/files/12045521/mdmCommand.log)
[mdmWorkflow.log](https://github.com/Macjutsu/super/files/12045522/mdmWorkflow.log)
[super.log](https://github.com/Macjutsu/super/files/12045523/super.log)

**Comment by Macjutsu** [comment] 2023-07-14 01:59
@redsee83 So... if you look at your mdmWorkflow.log.... we can see that all the older non-RSR updates are completing installation with a `PREPARED_COMMITTING_STASH`... however the log also shows that Apple's latest RSR update is not installing.

As you can see from this example mdmWorkflow.log... the RSR updates generate the same `PREPARED_COMMITTING_STASH` message upon completion. https://github.com/Macjutsu/super/blob/main/Example-Logs/13.3.1-%3E13.3.1(a)-Apple-Silicon-Jamf-Pro-MDM/mdmWorkflow.log

In other words, `super` is asking for an MDM update command to be sent and Jamf Pro is sending the MDM update command (as evidenced in the mdmCommand.log), but `softwareupdate` on that Mac isn't actually applying the RSR update.

Unfortunately there isn't anything `super` can do but try again later. You may have to manually restart that computer before `softwareupdate` actually starts working again. 

If you want support for using super please reach out to the [Mac Admins Foundation Slack](https://www.macadmins.org/) in channel [#super](https://macadmins.slack.com/archives/C03LKQ8EN2C).

**Comment by msmith-wenona** [comment] 2023-07-14 02:04
I too have adjusted the timeframes, but didn't get a time that worked.

my `mdmcommand.log` shows the below output

```
Sat Jul 08 16:14:56 FVFJ93UA1WG7 super[24976]: **** S.U.P.E.R.M.A.N. 3.0 INSTALL macOS Ventura 13.4.1-22F82 MDM START ****
Filtering the log data using "process == "softwareupdated" AND composedMessage CONTAINS "Reported progress""
2023-07-08 16:20:55.977 Df softwareupdated[29140:1b3bf] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
Timestamp               Ty Process[PID:TID]
2023-07-08 16:20:55.977 Df softwareupdated[29140:1b3bf] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:55.987 Df softwareupdated[29140:1b3bf] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_WAKEUP stalled:NO portionComplete:0.010000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:55.987 Df softwareupdated[29140:1b3bf] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_WAKEUP stalled:NO portionComplete:0.010000 estimatedTimeRemaining:-1.000000
Sat Jul 08 16:20:56 FVFJ93UA1WG7 super[24976]: **** TIMESTAMP ****
2023-07-08 16:20:56.768 Df softwareupdated[29140:1afe8] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_WAKEUP stalled:NO portionComplete:0.999000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:56.768 Df softwareupdated[29140:1afe8] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_WAKEUP stalled:NO portionComplete:0.999000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:56.769 Df softwareupdated[29140:1afe8] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:COMPLETED stalled:NO portionComplete:1.000000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:56.769 Df softwareupdated[29140:1afe8] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:COMPLETED stalled:NO portionComplete:1.000000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:57.901 Df softwareupdated[29140:1b3cb] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:57.902 Df softwareupdated[29140:1b3cb] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.750000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:57.901 Df softwareupdated[29140:1b3cb] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:57.902 Df softwareupdated[29140:1b3cb] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.750000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:58.420 Df softwareupdated[29140:1b3bf] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.999000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:58.421 Df softwareupdated[29140:1b3bf] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:COMPLETED stalled:NO portionComplete:1.000000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:58.420 Df softwareupdated[29140:1b3bf] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.999000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:58.421 Df softwareupdated[29140:1b3bf] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:COMPLETED stalled:NO portionComplete:1.000000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:58.668 Df softwareupdated[29140:1b3c4] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:58.668 Df softwareupdated[29140:1b3c4] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.750000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:58.668 Df softwareupdated[29140:1b3c4] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:58.668 Df softwareupdated[29140:1b3c4] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.750000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:59.219 Df softwareupdated[29140:1b3be] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.999000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:59.221 Df softwareupdated[29140:1b3be] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:COMPLETED stalled:NO portionComplete:1.000000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:59.219 Df softwareupdated[29140:1b3be] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.999000 estimatedTimeRemaining:-1.000000
2023-07-08 16:20:59.221 Df softwareupdated[29140:1b3be] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:COMPLETED stalled:NO portionComplete:1.000000 estimatedTimeRemaining:-1.000000
2023-07-08 16:21:18.099 Df softwareupdated[29140:1b3c1] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:21:18.099 Df softwareupdated[29140:1b3c1] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:21:18.195 Df softwareupdated[29140:1b716] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:READY stalled:NO portionComplete:0.990000 estimatedTimeRemaining:-1.000000
2023-07-08 16:21:18.195 Df softwareupdated[29140:1b716] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:READY stalled:NO portionComplete:0.990000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:20.172 Df softwareupdated[29140:1bb83] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:20.172 Df softwareupdated[29140:1bb83] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:ACCEPTED stalled:NO portionComplete:0.001000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:20.250 Df softwareupdated[29140:1bb83] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_WAKEUP stalled:NO portionComplete:0.010000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:20.250 Df softwareupdated[29140:1bb83] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_WAKEUP stalled:NO portionComplete:0.010000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:24.794 Df softwareupdated[29140:1ba02] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_WAKEUP stalled:NO portionComplete:0.079000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:24.794 Df softwareupdated[29140:1ba02] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_WAKEUP stalled:NO portionComplete:0.079000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:24.801 Df softwareupdated[29140:1ba02] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.080000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:24.801 Df softwareupdated[29140:1ba02] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.080000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:25.257 Df softwareupdated[29140:1ba02] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.149000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:25.257 Df softwareupdated[29140:1ba02] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:PREFLIGHT_PREREQUISITE stalled:NO portionComplete:0.149000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:25.278 Df softwareupdated[29140:1ba02] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_PERSONALIZE stalled:NO portionComplete:0.150000 estimatedTimeRemaining:-1.000000
2023-07-08 16:23:25.278 Df softwareupdated[29140:1ba02] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_PERSONALIZE stalled:NO portionComplete:0.150000 estimatedTimeRemaining:-1.000000
2023-07-08 16:24:03.362 Df softwareupdated[29140:1bb74] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_FDR_RECOVERY stalled:NO portionComplete:0.220000 estimatedTimeRemaining:-1.000000
2023-07-08 16:24:03.362 Df softwareupdated[29140:1bb74] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREFLIGHT_FDR_RECOVERY stalled:NO portionComplete:0.220000 estimatedTimeRemaining:-1.000000
2023-07-08 16:24:06.620 Df softwareupdated[29140:1bea4] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREPARING_UPDATE stalled:NO portionComplete:0.290000 estimatedTimeRemaining:-1.000000
2023-07-08 16:24:06.620 Df softwareupdated[29140:1bea4] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (start): phase:PREPARING_UPDATE stalled:NO portionComplete:0.290000 estimatedTimeRemaining:-1.000000
Sat Jul 08 16:24:06 FVFJ93UA1WG7 super[24976]: **** TIMESTAMP ****
2023-07-08 16:36:20.598 Df softwareupdated[29140:1d02e] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (inter): phase:PREPARING_UPDATE stalled:NO portionComplete:0.290035 estimatedTimeRemaining:-1.000000
2023-07-08 16:36:20.598 Df softwareupdated[29140:1d02e] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (inter): phase:PREPARING_UPDATE stalled:NO portionComplete:0.290035 estimatedTimeRemaining:-1.000000
2023-07-08 16:38:59.188 Df softwareupdated[29140:1d3a5] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (inter): phase:PREPARING_UPDATE stalled:NO portionComplete:0.297156 estimatedTimeRemaining:-1.000000
2023-07-08 16:38:59.188 Df softwareupdated[29140:1d3a5] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (inter): phase:PREPARING_UPDATE stalled:NO portionComplete:0.297156 estimatedTimeRemaining:-1.000000
2023-07-08 16:41:21.584 Df softwareupdated[29140:1d741] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (inter): phase:PREPARING_UPDATE stalled:NO portionComplete:0.304269 estimatedTimeRemaining:-1.000000
2023-07-08 16:41:21.584 Df softwareupdated[29140:1d741] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (inter): phase:PREPARING_UPDATE stalled:NO portionComplete:0.304269 estimatedTimeRemaining:-1.000000
2023-07-08 16:43:55.926 Df softwareupdated[29140:1f94c] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (inter): phase:PREPARING_UPDATE stalled:NO portionComplete:0.311582 estimatedTimeRemaining:-1.000000
2023-07-08 16:43:55.926 Df softwareupdated[29140:1f94c] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (inter): phase:PREPARING_UPDATE stalled:NO portionComplete:0.311582 estimatedTimeRemaining:-1.000000
2023-07-08 16:44:33.646 Df softwareupdated[29140:20ae8] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:COMPLETED stalled:NO portionComplete:1.000000 estimatedTimeRemaining:-1.000000
2023-07-08 16:44:33.646 Df softwareupdated[29140:20ae8] [com.apple.SoftwareUpdateMacController:SU] [SUMacControllerProgressManager] Reported progress (end): phase:COMPLETED stalled:NO portionComplete:1.000000 estimatedTimeRemaining:-1.000000
```
So it gets to the preparing_update stage and only does about 30%-50% and then moves to completed
BUT doesn't actually complete and never gets to Applying.

full mdmworkflow.log below
[mdmWorkflow.log](https://github.com/Macjutsu/super/files/12045667/mdmWorkflow.log)

**Comment by redsee83** [comment] 2023-07-14 13:23
rebooted but same result of failure.

**Comment by Macjutsu** [comment] 2023-07-14 14:59
The permissions issue has been resolved... the issue that your seeing now is a duplicate of https://github.com/Macjutsu/super/issues/107

**Closed by Macjutsu** 2023-07-14 14:59 UTC
Labels: duplicate
